version: "3.7"

services:
  server:
    build: ./server
    container_name: server
    depends_on:
      - mongo
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/app
    environment:
      - DEBUG=server
    working_dir: /usr/src/app
    command: npm run dev
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/mongo-data:/data/db
    

